export { default as Arrow } from './Arrow'
export { default as Error } from './Error'
export { default as Favorite } from './Favorite'
export { default as Hospital } from './Hospital'
export { default as Payment } from './Paypment'
export { default as Phone } from './Phone'
export { default as Shield } from './Shield'
